linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 13 # Should be 10 but was brought to 13 to speed up the development
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

  misspell:
    locale: US

  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 130

# options for analysis running
run:
  build-tags:
    - functional

linters:
  enable-all: false
  disable:
  - prealloc
  - dupl